# tornado-blank-project

# Configuration

PYTHON="/path/to/python"
EASYINSTALL="/path/to/easy_install"
NOSETESTS="/path/to/nosetests"

# Targets

PYTHONPATH="`pwd`/src"

server:
	export PYTHONPATH=${PYTHONPATH} && cd src && ${PYTHON} server.py

console:
	export PYTHONPATH=${PYTHONPATH} && cd src && ${PYTHON}

test:
	${NOSETESTS} -i should -i spec --verbose --nocapture

database:
	mkdir -p data
	export PYTHONPATH=${PYTHONPATH} && cd src/ && ${PYTHON} util/database.py

deps:
	${EASYINSTALL} tornado
	${EASYINSTALL} sqlalchemy
	${EASYINSTALL} nose
	${EASYINSTALL} mockito

clean:
	find . -name *.pyc -exec rm {} \;

.PHONY: server test database clean